docs: ARS merkelization to proposed
witnet/WIPs pull request #33
Opened 2021-01-12 09:32 UTC by girazoki

2021-01-12 13:41 UTC, aesedepece approved these changes

2021-01-12 13:42 UTC, aesedepece requested changes
Please also move to Proposed in README.md

2021-01-21 10:28 UTC, aesedepece approved these changes

2021-01-21 12:49 UTC, mariocao approved these changes

2021-01-26 14:44 UTC, merged